
export const userData=[{
    "id": 1,
    "first_name": "Kim",
    "last_name": "Shortt",
    "email": "kshortt0@wordpress.org",
    "gender": "Female"
  }, {
    "id": 2,
    "first_name": "Darlleen",
    "last_name": "Blagburn",
    "email": "dblagburn1@vistaprint.com",
    "gender": "Genderqueer"
  }, {
    "id": 3,
    "first_name": "Gabi",
    "last_name": "Ragate",
    "email": "gragate2@wix.com",
    "gender": "Male"
  }, {
    "id": 4,
    "first_name": "Boycie",
    "last_name": "Chaston",
    "email": "bchaston3@t-online.de",
    "gender": "Male"
  }, {
    "id": 5,
    "first_name": "Margarete",
    "last_name": "Konrad",
    "email": "mkonrad4@mozilla.com",
    "gender": "Genderfluid"
  }, {
    "id": 6,
    "first_name": "Javier",
    "last_name": "Brisbane",
    "email": "jbrisbane5@wired.com",
    "gender": "Male"
  }, {
    "id": 7,
    "first_name": "Sharia",
    "last_name": "Satterley",
    "email": "ssatterley6@rakuten.co.jp",
    "gender": "Female"
  }, {
    "id": 8,
    "first_name": "Glynnis",
    "last_name": "Gutcher",
    "email": "ggutcher7@vinaora.com",
    "gender": "Female"
  }, {
    "id": 9,
    "first_name": "Rolf",
    "last_name": "Steart",
    "email": "rsteart8@disqus.com",
    "gender": "Male"
  }, {
    "id": 10,
    "first_name": "Wayland",
    "last_name": "Burles",
    "email": "wburles9@eepurl.com",
    "gender": "Male"
  }]
